# 12. MODEL INFERENCE

## A. Libraries

In [17]:
import pandas as pd
import numpy as np
import pickle
import json

## B. Model Load

In [37]:
with open('data_kmeans.pkl', 'rb') as file_1:
  km_el = pickle.load(file_1)

with open('model_scaler_skew.pkl', 'rb') as file_2:
  scaler_skew = pickle.load(file_2)

with open('model_scaler_normal.pkl', 'rb') as file_3:
  scaler_nor = pickle.load(file_3)

with open('list_num_column_skew.txt', 'rb') as file_4:
  df_cols = json.load(file_4)

with open('list_num_column_normal.txt', 'rb') as file_5:
  df_coln = json.load(file_5)

## C. Data Inference

In [40]:
data_inf = {'cust_id': {2: 6075, 3: 6291, 4: 7755, 5: 8299},
 'balance': {2: 757.964752, 3: 264.566591, 4: 440.613643, 5: 611.561026},
 'balance_frequency': {2: 0.875, 3: 0.375, 4: 1.0, 5: 1.0},
 'purchases': {2: 157.4, 3: 1150.0, 4: 600.0, 5: 765.0},
 'oneoff_purchases': {2: 157.4, 3: 1150.0, 4: 600.0, 5: 765.0},
 'installments_purchases': {2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0},
 'cash_advance': {2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0},
 'purchases_frequency': {2: 0.125, 3: 0.125, 4: 0.125, 5: 0.125},
 'oneoff_purchases_frequency': {2: 0.125, 3: 0.125, 4: 0.125, 5: 0.125},
 'purchases_installments_frequency': {2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0},
 'cash_advance_frequency': {2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0},
 'cash_advance_trx': {2: 0, 3: 0, 4: 0, 5: 0},
 'purchases_trx': {2: 6, 3: 1, 4: 1, 5: 1},
 'credit_limit': {2: 1200.0, 3: 1200.0, 4: 1000.0, 5: 2000.0},
 'payments': {2: 1494.480376, 3: 3029.380326, 4: 215.316424, 5: 204.464151},
 'minimum_payments': {2: 2638.59841,
  3: 85.428885,
  4: 137.846006,
  5: 146.352314},
 'prc_full_payment': {2: 0.0, 3: 0.0, 4: 0.0, 5: 0.0},
 'tenure': {2: 8, 3: 8, 4: 8, 5: 8},
 'cluster_elbow': {2: 1, 3: 1, 4: 1, 5: 1},
 'cluster_silhoutte': {2: 1, 3: 1, 4: 1, 5: 1},
 'cluster_silhouette': {2: 1, 3: 1, 4: 1, 5: 1}}

data_inf = pd.DataFrame(data_inf)

data_inf.info()
data_inf

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 2 to 5
Data columns (total 21 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   cust_id                           4 non-null      int64  
 1   balance                           4 non-null      float64
 2   balance_frequency                 4 non-null      float64
 3   purchases                         4 non-null      float64
 4   oneoff_purchases                  4 non-null      float64
 5   installments_purchases            4 non-null      float64
 6   cash_advance                      4 non-null      float64
 7   purchases_frequency               4 non-null      float64
 8   oneoff_purchases_frequency        4 non-null      float64
 9   purchases_installments_frequency  4 non-null      float64
 10  cash_advance_frequency            4 non-null      float64
 11  cash_advance_trx                  4 non-null      int64  
 12  purchases_trx    

cust_id     balance  balance_frequency  purchases  oneoff_purchases  \
2     6075  757.964752              0.875      157.4             157.4   
3     6291  264.566591              0.375     1150.0            1150.0   
4     7755  440.613643              1.000      600.0             600.0   
5     8299  611.561026              1.000      765.0             765.0   

   installments_purchases  cash_advance  purchases_frequency  \
2                     0.0           0.0                0.125   
3                     0.0           0.0                0.125   
4                     0.0           0.0                0.125   
5                     0.0           0.0                0.125   

   oneoff_purchases_frequency  purchases_installments_frequency  ...  \
2                       0.125                               0.0  ...   
3                       0.125                               0.0  ...   
4                       0.125                               0.0  ...   
5                       0.125                               0.0  ...   

   cash_advance_trx  purchases_trx  credit_limit     payments  \
2                 0              6        1200.0  1494.480376   
3                 0              1        1200.0  3029.380326   
4                 0              1        1000.0   215.316424   
5                 0              1        2000.0   204.464151   

   minimum_payments  prc_full_payment  tenure  cluster_elbow  \
2       2638.598410               0.0       8              1   
3         85.428885               0.0       8              1   
4        137.846006               0.0       8              1   
5        146.352314               0.0       8              1   

   cluster_silhoutte  cluster_silhouette  
2                  1                   1  
3                  1                   1  
4                  1                   1  
5                  1                   1  

[4 rows x 21 columns]

## D. Numeric & Categoric Split

In [41]:
data_num_s = data_inf[df_cols]
data_num_n = data_inf[df_coln]


display(df_cols)
display(df_coln)

['balance',
 'balance_frequency',
 'purchases',
 'oneoff_purchases',
 'installments_purchases',
 'cash_advance',
 'oneoff_purchases_frequency',
 'cash_advance_frequency',
 'cash_advance_trx',
 'purchases_trx',
 'credit_limit',
 'payments',
 'prc_full_payment',
 'tenure']

['purchases_frequency', 'purchases_installments_frequency']

## E. Scale & Encode

In [42]:
print(data_num_s.dtypes)
print(data_num_n.dtypes)


balance                       float64
balance_frequency             float64
purchases                     float64
oneoff_purchases              float64
installments_purchases        float64
cash_advance                  float64
oneoff_purchases_frequency    float64
cash_advance_frequency        float64
cash_advance_trx                int64
purchases_trx                   int64
credit_limit                  float64
payments                      float64
prc_full_payment              float64
tenure                          int64
dtype: object
purchases_frequency                 float64
purchases_installments_frequency    float64
dtype: object


In [43]:
# skew
data_inf_num_s = scaler_skew.transform(data_num_s)
# normal
data_inf_num_n = scaler_nor.transform(data_num_n)

display(data_inf_num_s)
display(data_inf_num_n)

array([[0.09651228, 0.82903428, 0.02157542, 0.02788561, 0.        ,
        0.        , 0.125     , 0.        , 0.        , 0.06461265,
        0.07487953, 0.14589917, 0.        , 0.08140924],
       [0.03368748, 0.14517141, 0.1576349 , 0.20373859, 0.        ,
        0.        , 0.125     , 0.        , 0.        , 0.01076878,
        0.07487953, 0.29574928, 0.        , 0.08140924],
       [0.0561037 , 1.        , 0.08224429, 0.10629839, 0.        ,
        0.        , 0.125     , 0.        , 0.        , 0.01076878,
        0.06185701, 0.0210162 , 0.        , 0.08140924],
       [0.07787057, 1.        , 0.10486147, 0.13553045, 0.        ,
        0.        , 0.125     , 0.        , 0.        , 0.01076878,
        0.12696964, 0.01995671, 0.        , 0.08140924]])

array([[-0.92146472, -0.92428962],
       [-0.92146472, -0.92428962],
       [-0.92146472, -0.92428962],
       [-0.92146472, -0.92428962]])

## F. Concatenate

In [44]:
data_inf_final = np.concatenate([data_inf_num_s, data_inf_num_n], axis=1)

data_inf_final

array([[ 0.09651228,  0.82903428,  0.02157542,  0.02788561,  0.        ,
         0.        ,  0.125     ,  0.        ,  0.        ,  0.06461265,
         0.07487953,  0.14589917,  0.        ,  0.08140924, -0.92146472,
        -0.92428962],
       [ 0.03368748,  0.14517141,  0.1576349 ,  0.20373859,  0.        ,
         0.        ,  0.125     ,  0.        ,  0.        ,  0.01076878,
         0.07487953,  0.29574928,  0.        ,  0.08140924, -0.92146472,
        -0.92428962],
       [ 0.0561037 ,  1.        ,  0.08224429,  0.10629839,  0.        ,
         0.        ,  0.125     ,  0.        ,  0.        ,  0.01076878,
         0.06185701,  0.0210162 ,  0.        ,  0.08140924, -0.92146472,
        -0.92428962],
       [ 0.07787057,  1.        ,  0.10486147,  0.13553045,  0.        ,
         0.        ,  0.125     ,  0.        ,  0.        ,  0.01076878,
         0.12696964,  0.01995671,  0.        ,  0.08140924, -0.92146472,
        -0.92428962]])

## G. Predict

In [47]:
pred_inf = km_el.predict(data_inf_final)

pred_inf

ValueError: X has 16 features, but KMeans is expecting 7 features as input.

## H. Concatenate Prediction

In [46]:
pred_inf_df = pd.DataFrame(data_inf_final, columns=['Prediction'])

pred_inf_df

ValueError: Shape of passed values is (4, 16), indices imply (4, 1)

In [27]:
data_inf_pred = pd.concat([data_inf, pred_inf_df], axis=1)

data_inf_pred

NameError: name 'pred_inf_df' is not defined